[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = DrBattery2026

session_gc = 54000
http_port = 8070
proxy_mode = True
workers = 0

; Conexión a la BD en el Host
db_host = 127.0.0.1
db_port = 5432
db_user = odoo_dev_user
db_password = DrBattery


